from x4.types import Resource, Tier
from x4_data.races import TELADI

TIERS = [
    Tier(
        0,
        "Harvested",
        [
            Resource(name="Helium"),
            Resource(name="Methane"),
            Resource(name="Ore"),
            Resource(name="Hydrogen"),
            Resource(name="Silicon"),
            Resource(name="Nividium"),
            Resource(name="Raw Scrap", tags={"recycling"}),
            Resource(name="Scrap Metal", recipes={"Universal": {"Raw Scrap"}}, tags={"recycling"}),
            Resource(name="Ice"),
            Resource(name="Water", recipes={"Universal": {"Ice"}}),
        ],
    ),
    Tier(
        1,
        "Basic Food",
        [
            Resource(name="Wheat", race="Argon", recipes={"Universal": {"Water"}}),
            Resource(name="Meat", race="Argon", recipes={"Universal": {"Water"}}),
            Resource(name="Maja Snails", recipes={"Universal": {"Water"}}),
            Resource(name="Soja Beans", recipes={"Universal": {"Water"}}),
            Resource(name="Swamp Plant", recipes={"Universal": {"Water"}}),
            Resource(name="Spices", recipes={"Universal": {"Water"}}),
            Resource(name="BoGas", recipes={"Universal": {"Water"}}),
            Resource(name="Chelt Meat", recipes={"Universal": {"Water"}}),
            Resource(name="Protein Paste", recipes={"Terran": {"Ice", "Methane"}}),
            Resource(name="Scruffin Fruit", recipes={"Universal": {"Water"}}),
            Resource(name="Sunrise Flowers", recipes={"Universal": {"Water"}}),
            Resource(name="Plankton", recipes={"Universal": {"Water"}}),
        ],
    ),
    Tier(
        2,
        "Food and Drugs",
        [
            Resource(name="Spacefuel", recipes={"Universal": {"Wheat", "Water"}}),
            Resource(name="Food Rations", race="Argon", recipes={"Universal": {"Meat", "Spices", "Wheat"}}),
            Resource(name="Maja Dust", recipes={"Universal": {"Maja Snails", "Spices"}}),
            Resource(name="Soja Husk", recipes={"Universal": {"Maja Snails", "Soja Beans", "Spices"}}),
            Resource(name="Space Weed", recipes={"Universal": {"Spices", "Swamp Plant"}}),
            Resource(name="Nostrop Oil", recipes={"Universal": {"Spices", "Sunrise Flowers", "Water"}}),
            Resource(
                name="Medical Supplies",
                recipes={
                    "Universal": {"Spices", "Water", "Wheat"},
                    "Paranid": {"Soja Beans", "Spices", "Water"},
                    "Split": {"Scruffin Fruit", "Spices", "Water"},
                    "Teladi": {"Spices", "Sunrise Flowers", "Water"},
                    "Terran": {"Ice", "Protein Paste"},
                    "Boron": {"Water", "Plankton"},
                },
            ),
            Resource(name="Terran MRE", recipes={"Terran": {"Protein Paste"}}),
            Resource(name="Stimulants", recipes={"Terran": {"Helium", "Silicon"}}),
            Resource(name="BoFu", recipes={"Universal": {"BoGas", "Plankton"}}),
        ],
    ),
    Tier(
        3,
        "Refined",
        [
            Resource(name="Superfluid Coolant", recipes={"Universal": {"Helium"}}),
            Resource(name="Graphene", recipes={"Universal": {"Methane"}}),
            Resource(name="Refined Metals", recipes={"Universal": {"Ore"}}),
            Resource(name="Teladianium", race=TELADI, colour="lime", recipes={"Universal": {"Ore"}}),
            Resource(name="Antimatter Cells", recipes={"Universal": {"Hydrogen"}}),
            Resource(name="Silicon Wafers", recipes={"Universal": {"Silicon"}}),
            Resource(name="Computronic Substrate", recipes={"Terran": {"Hydrogen", "Ore", "Silicon"}, "Recycling": {"Scrap Metal"}}),
            Resource(name="Metallic Microlattice", recipes={"Terran": {"Helium", "Ore"}}),
        ],
    ),
    Tier(
        4,
        "Advanced",
        [
            Resource(name="Plasma Conductors", recipes={"Universal": {"Graphene", "Superfluid Coolant"}}),
            Resource(name="Quantum Tubes", colour="palevioletred1", recipes={"Universal": {"Graphene", "Superfluid Coolant"}}),
            Resource(name="Advanced Composites", recipes={"Universal": {"Graphene", "Refined Metals"}, "Teladi": {"Graphene", "Teladianium"}}),
            Resource(name="Hull Parts", colour="royalblue", recipes={"Universal": {"Graphene", "Refined Metals"}, "Teladi": {"Graphene", "Teladianium"}, "Recycling": {"Scrap Metal"}}),
            Resource(name="Engine Parts", colour="mediumseagreen", recipes={"Universal": {"Antimatter Cells", "Refined Metals"}, "Teladi": {"Antimatter Cells", "Teladianium"}}),
            Resource(name="Microchips", colour="limegreen", recipes={"Universal": {"Silicon Wafers"}}),
            Resource(name="Smart Chips", recipes={"Universal": {"Silicon Wafers"}}),
            Resource(name="Silicon Carbide", recipes={"Terran": {"Metallic Microlattice", "Methane", "Silicon"}, "Recycling": {"Scrap Metal"}}),
        ],
    ),
    Tier(
        5,
        "Components",
        [
            Resource(name="Drone Components", recipes={"Universal": {"Engine Parts", "Hull Parts", "Microchips", "Scanning Arrays"}}),
            Resource(name="Turret Components", recipes={"Universal": {"Microchips", "Quantum Tubes", "Scanning Arrays"}}),
            Resource(name="Missile Components", recipes={"Universal": {"Advanced Composites", "Hull Parts"}}),
            Resource(name="Field Coils", recipes={"Universal": {"Plasma Conductors", "Quantum Tubes"}}),
            Resource(name="Shield Components", recipes={"Universal": {"Plasma Conductors", "Quantum Tubes"}}),
            Resource(name="Antimatter Converters", recipes={"Universal": {"Microchips", "Advanced Composites"}}),
            Resource(name="Weapon Components", recipes={"Universal": {"Hull Parts", "Plasma Conductors"}}),
            Resource(name="Scanning Arrays", colour="orange1", recipes={"Universal": {"Refined Metals", "Silicon Wafers"}, "Teladi": {"Teladianium", "Silicon Wafers"}}),
            Resource(name="Claytronics", colour="hotpink1", recipes={"Universal": {"Antimatter Cells", "Microchips", "Quantum Tubes"}, "Recycling": {"Scrap Metal"}}),
            Resource(name="Advanced Electronics", recipes={"Universal": {"Microchips", "Quantum Tubes"}}),
        ],
    ),
    Tier(
        6,
        "Equipment",
        [
            Resource(name="Ship Hulls", recipes={"Universal": {"Hull Parts"}}, tags={"terminal"}),
            Resource(name="Nav Beacons", recipes={"Universal": {"Hull Parts"}}, tags={"terminal"}),
            Resource(name="Missiles", recipes={"Universal": {"Missile Components", "Smart Chips"}}, tags={"terminal"}),
            Resource(name="Station modules", colour="hotpink1", recipes={"Universal": {"Hull Parts", "Claytronics"}}, tags={"terminal"}),
            Resource(name="Engines", colour="hotpink1", recipes={"Universal": {"Antimatter Converters", "Engine Parts"}}, tags={"terminal"}),
            Resource(name="Thrusters", colour="hotpink1", recipes={"Universal": {"Antimatter Converters", "Engine Parts"}}, tags={"terminal"}),
            Resource(name="Mines", recipes={"Universal": {"Weapon Components", "Smart Chips"}}, tags={"terminal"}),
            Resource(name="Drones", recipes={"Universal": {"Drone Components", "Smart Chips"}}, tags={"terminal"}),
            Resource(name="Laser Towers", recipes={"Universal": {"Drone Components", "Smart Chips"}}, tags={"terminal"}),
            Resource(name="Shields", colour="hotpink1", recipes={"Universal": {"Field Coils", "Shield Components"}}, tags={"terminal"}),
            Resource(name="Turrets", colour="hotpink1", recipes={"Universal": {"Turret Components", "Advanced Electronics"}}, tags={"terminal"}),
            Resource(name="Guns and Launchers", colour="hotpink1", recipes={"Universal": {"Advanced Electronics", "Weapon Components"}}, tags={"terminal"}),
            Resource(name="Satellites", recipes={"Universal": {"Scanning Arrays", "Advanced Electronics", "Hull Parts"}}, tags={"terminal"}),
        ],
    ),
]
